test: add more tests in integration test

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -33,7 +33,9 @@ jobs:
 
       - name: Adding data to the config.yml
         run: |
+          PICASSO_TUTOR_VERSION=$(tutor --version | awk '{print $NF}')
           cat <<EOF >> config.yml
+          PICASSO_TUTOR_VERSION: $PICASSO_TUTOR_VERSION
           PICASSO_MANAGE_DPKG:
             name: eox-manage
             repo: git@github.com:eduNEXT/eox-manage.git
@@ -42,6 +44,13 @@ jobs:
             - name: endx-saas-themes
               repo: git@github.com:eduNEXT/ednx-saas-themes.git
               version: master
+          PICASSO_THEME_DIRS:
+          - /openedx/themes/ednx-saas-themes/edx-platform
+          - /openedx/themes/ednx-saas-themes/edx-platform/bragi-generator
+          - /openedx/themes/ednx-saas-themes/edx-platform/bragi-children
+          PICASSO_THEMES_NAME:
+          - bragi
+          - css-runtime
           PICASSO_EXTRA_COMMANDS:
             - tutor plugins update
             - tutor plugins index add https://raw.githubusercontent.com/eduNEXT/tutor-plugin-indexes/picasso_test/
@@ -57,6 +66,27 @@ jobs:
       - name: Check enable-themes
         run: |
           TUTOR_ROOT="$(pwd)" tutor picasso enable-themes
+
+          if grep -q 'bragi' env/build/openedx/Dockerfile; then
+            echo "'bragi' found in env/build/openedx/Dockerfile."
+          else
+            echo "'bragi' not found for the building process."
+            exit 1
+          fi
+
+          if grep -q '/openedx/themes/ednx-saas-themes/edx-platform' env/build/openedx/Dockerfile; then
+            echo "'/openedx/themes/ednx-saas-themes/edx-platform' found in env/build/openedx/Dockerfile."
+          else
+            echo "'/openedx/themes/ednx-saas-themes/edx-platform' not found for the building process."
+            exit 1
+          fi
+
+          if grep -q 'ENABLE_COMPREHENSIVE_THEMING = True' env/apps/openedx/settings/lms/production.py; then
+            echo "'ENABLE_COMPREHENSIVE_THEMING = True' found in env/apps/openedx/settings/lms/production.py."
+          else
+            echo "'ENABLE_COMPREHENSIVE_THEMING = True' not found in env/apps/openedx/settings/lms/production.py."
+            exit 1
+          fi
 
       - name: Check enable-private-packages
         run: |
